### ISSUE TITLE
High praise, and a feature request

### ISSUE THREAD

**Issue by raiguard** [crizan/kak-rainbower#1]
This is absolutely stupendous! It's amazing how well this plugin works - once compiled, it just... works. It's beautiful, and ironic that it works so well considering how niche of an editor Kakoune is.

I do have one feature request: I see that `<>` are occasionally rainbowed if you have a certain setting turned on for C. However, there are other places it is used as well. For example, in Rust, you get situations like this:

![Screenshot from 2021-04-02 00-35-19](https://user-images.githubusercontent.com/3515394/113388369-57373c00-934b-11eb-9dd3-9667ebe80b80.png)

The parenthesis and braces are rainbowed nicely, but the nested angle brackets on line 221 are not. It would be very nice if these could be rainbowed. I'm not sure what kind of regex magic or syntax awareness would be required (angle brackets are used in several other places), but hopefully it wouldn't be too bad.

Thanks again for the amazing plugin! It's seriously amazing how well it works, I'm floored.

**Comment by crizan** [comment]
I now have implemented this
It's still not amazing (like in the cpp one a < 0 && a > 9 gets detected as generic) but it should not be terrible either

(thanks anyway, I'm happy to hear that you like this simple plugin)

**Comment by raiguard** [comment]
Thank you! I've given it a spin and it appears to work very well! However, it is completely missing turbofishes, like in the original screenshot that I posted. If that can be fixed, then it will be practically perfect! :heart: 

Thanks again for the amazing plugin.

**Comment by crizan** [comment]
Can you tell me if removing all other highlighters it works?

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/113520393-07759200-9550-11eb-9ab7-46b2fd49cb1f.png)

I removed all the highlighters I could, but it didn't change anything.

**Comment by crizan** [comment]
Have you set rainbow_check_templates to Y? By default is disabled

**Comment by raiguard** [comment]
Yes. It works in other places, but not specifically the `::<Something>()` syntax (turbofish).

There are also some other edge cases, but you did say that it wasn't perfect:

![image](https://user-images.githubusercontent.com/3515394/113520543-04c76c80-9551-11eb-9c89-e026e8c29a03.png)

Edit: oh, it's just counting the `->` as the closing one. I don't envy the parsing you have to do for this!

Edit 2: just noticed that Kakoune itself also mistakes the `->` for the closing pair. I'll open an issue about that upstream as well.

**Comment by crizan** [comment]
I can fix the arrow one in reality
To me it appears like this, hence why I'm confused
![2021-04-04-222406_1920x1080_scrot](https://user-images.githubusercontent.com/48642291/113520621-95736c00-9594-11eb-8e40-308ab0803a74.png)
I will try to understand the problem with your code in particular

**Comment by raiguard** [comment]
The code I'm using is from [kak-lsp](https://github.com/kak-lsp/kak-lsp), in `main.rs` on line `221`.

The code for the arrow one is `context.rs` on line `23`.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/113520724-705e0980-9552-11eb-9a02-c4d248e90c5c.png)

Huh, it works just fine in this case. I guess something about kak-lsp specifically is tripping it up.

**Comment by crizan** [comment]
Ok, I found the problem and pushed the fix, (I'm making too many typos, and clangd for some reason has not told me anything)
The arrow should also be ignored now

**Comment by raiguard** [comment]
Confirmed fixed! Thanks for all your work. :heart:
