### ISSUE TITLE
[Bug] Rust comment containing a double quote breaks rainbowing after it

### ISSUE THREAD

**Issue by raiguard** [crizan/kak-rainbower#2]
![image](https://user-images.githubusercontent.com/3515394/113518889-528aa780-9546-11eb-8376-e60f7a68e16e.png)

On line 19 of the above screenshot, I have a comment that contains a double quote `"`. The instant you put a double quote inside a comment, every rainbowed thing after that point will revert to default and will not be rainbowed again until you remove the `"`.

I tested Rust and Lua, and it only happens with Rust. I also reverted to a commit before you added the `<>` highlighting to Rust, and it still happened there.

**Comment by crizan** [comment]
I'm pretty sure that this bug was included by that commit, but now it should work properly

**Comment by raiguard** [comment]
Confirmed, thanks for the fix! It's possible that I didn't recompile correctly or something when I tested the earlier commit.
