### ISSUE TITLE
Locks up entire kakoune server when opening large files

### ISSUE THREAD

**Issue by raiguard** [crizan/kak-rainbower#7]
When I open certain files in my work C++ codebase, the buffer opens but kakoune immediately freezes. The entire server hangs indefinitely and I need to send a SIGKILL to the server to close it. It appears to occur on very large files - specifically, this file is 6,530 lines long and contains 12,228 instances of `[\{\[\(\)\]\}<>]`.

I have `rainbow_mode = 0` and `rainbow_check_templates = Y`. Unfortunately I cannot provide the file for testing.

**Comment by crizan** [comment]
It used to work with pretty large files, but I checked now and I also can reproduce the same issue. It seems like it executes just fine but when I send back the ranges to highlight to kakoune it just locks up. I will take a look at it

**Comment by crizan** [comment]
I have pushed a fix that works on my end, could you check if it fixes the issue for you?

**Comment by raiguard** [comment]
It appears to work! Thank you.
I found another error in the debug buffer but I will open a new issue for that.
